// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wunrwaoyjgeqpwnhvjxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bnJ3YW95amdlcXB3bmh2anhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjY2MjIsImV4cCI6MjA2MzA0MjYyMn0.EuA86Q5rm4l4FfTK6qayq9kWm7Kbmc10T3h3K5MxcUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);